### ISSUE TITLE
Receipt shows NO items

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#619] opened 2016-01-16 16:09 UTC
Currently, whether I select "Modular" or either of the "legacy" receipt printing settings, our CORE-POS (1.9) installation is printing no items whatsoever on the receipt. It goes straight from the date/time row to "TODAY YOU SAVED = $x.xx" and "thank you - owner ####".

Any clues what might cause this?

**Comment by gohanman** [comment] 2016-01-16 16:14
What do reprints (RP) do?

**Comment by flathat** [comment] 2016-01-16 17:28
Are there any errors in `$LANE/log/php-errors.log` or `queries.log`. See Install > Debug for actual logfile names.

**Comment by scannerdarkly** [comment] 2016-01-16 19:51
Reprints show the same (lack of information), except the "TODAY YOU SAVED" line is gone as well.

**Comment by gohanman** [comment] 2016-01-16 19:57
Sounds like perhaps info not going into localtranstoday correctly. Eric's query log suggestion might be informative. 

Otherwise some oddity in ReceiptLib::receiptDetail

**Comment by scannerdarkly** [comment] 2016-01-16 21:03
Cleared the logs, then did a one-item transaction.

**queries.log:**
```
Failed Query on /lane/ajax-callbacks/ajax-end.
select linetoprint,sequence,dept_name,ordered, 0 as \`local\` from rp_receipt_reorder_unions_g where emp_no=9999 and  register_no=1 and trans_no=6  order by ordered.dept_name,  case when ordered=4 then '' else upc end, `sequence`
Unknown column 'emp_no' in 'where clause'
```
**php-errors.log** remains empty.

**Comment by scannerdarkly** [comment] 2016-01-16 21:20
To my knowledge, we have done no schema changes from the default 1.9 install.

**Comment by flathat** [comment] 2016-01-16 21:58
Is translog.rp_receipt_reorder_unions_g.emp_no there in mysql/phpMyAdmin? It's a view, not a table.

Look at lane Install > DB Updates and apply any suggested changes that seem pertinent, which will rebuild views.

If that doesn't help we can see about rebuilding the view manually.

**Comment by scannerdarkly** [comment] 2016-01-16 22:15
Lane Install > DB Updates suggested two changes. I ran them both, still no change to how the receipt is printing. The translog.rp_receipt_reorder_unions_g view shows only five fields right now: linetoprint, sequence, dept_name, ordered, and upc.

**Comment by gohanman** [comment] 2016-01-16 22:16
DB Updates are completely unaware of these legacy views; there's never been
any real intention to support them forever.

The install script does appear to be wrong on those views but I have mixed
feeling about sinking time into fixing them. They've been listed as
potentially unsupported for 13 releases (or a year and a half plus). In any
event, those views have nothing whatsoever to do with the default, modular
receipt so it doesn't fully explain the problem.

**Comment by scannerdarkly** [comment] 2016-01-16 22:18
Would it be halpful for me to switch back to the modular receipt and see if the error messages are different?

**Comment by gohanman** [comment] 2016-01-16 22:21
Yes, that's definitely the preferred option. The
rp_receipt_reorder_unions_g view is pretty ugly and sits on top of three
more equally ugly view layers - which is both why it got replaced and why
I'm not terribly enthused to dig around in it.

**Comment by scannerdarkly** [comment] 2016-01-16 22:43
Sadly, having switched over to Modular, logged out. logged back in, cleared both logs, and done another single-item transaction, both **queries.log** and **php-errors.log** have returned to being exactly as I reported earlier. Except date and trans_no reported in the error message are different. :)

I repeated the test twice just now, just be sure I wasn't tricking myself.

**Comment by gohanman** [comment] 2016-01-16 22:50
As in the query log still refers to rp_receipt_reorder_unions_g? That is
baffling. That would imply settings are being completely ignored somehow.

**Comment by scannerdarkly** [comment] 2016-01-16 22:52
That is correct. I'm changing these settings on the local lane. This lane has been controlled by office in the past; would that cause it to ignore local settings changes? (When I talked with Eric Lee earlier, he seemed to feel not, but perhaps I misunderstood him.)

**Comment by scannerdarkly** [comment] 2016-01-16 22:52
Should I attach ini.php and ini-local.php?

**Comment by gohanman** [comment] 2016-01-16 23:08
This is a setting that should be in the parameters table. It should
automatically erase settings from ini.php that don't belong there (if
permissions allow) but I don't think it'll automatically deal with any sort
of mess in ini-local.php.

**Comment by scannerdarkly** [comment] 2016-01-17 00:15
**core_opdata.parameters** table
"0","0","alertBar",,"0"
"0","0","BottleReturnDept",,"0"
"0","0","cashOverLimit","0","0"
"0","0","CouponsAreTaxable","1","0"
"0","0","CustomerDisplay","0","0"
"0","0","Debug_CoreLocal","0","0"
"0","0","Debug_Redirects","0","0"
"0","0","defaultNonMem","99999","0"
"0","0","DiscountableSaleItems","1","0"
"0","0","discountEnforced","0","0"
"0","0","DiscountModule","DiscountModule","0"
"0","0","DiscountTypeClasses",,"1"
"0","0","dollarOver","0","0"
"0","0","dualDrawerMode","0","0"
"0","0","EanIncludeCheckDigits","0","0"
"0","0","emailReceiptFrom",,"0"
"0","0","enableFranking","0","0"
"0","0","fntlDefault","1","0"
"0","0","FooterModules","SavedOrCouldHave,TransPercentDiscount,MemSales,EveryoneSales,MultiTotal","1"
"0","0","houseCouponPrefix","00499999","0"
"0","0","kickerModule","Kicker","0"
"0","0","LineItemDiscountMem","0","0"
"0","0","LineItemDiscountNonMem","0","0"
"0","0","lockScreen","0","0"
"0","0","LoudLogins","0","0"
"0","0","mDatabase","core_trans","0"
"0","0","mDBMS","mysqli","0"
"0","0","member_subtotal","1","0"
"0","0","memlistNonMember","0","0"
"0","0","mPass",,"0"
"0","0","mServer","127.0.0.1","0"
"0","0","mUser","\*\*\*\*\*\*\*\*","0"
"0","0","newReceipt","2","0"
"0","0","Notifiers",,"1"
"0","0","OS","other","0"
"0","0","PluginList",,"1"
"0","0","PriceMethodClasses",,"1"
"0","0","print","0","0"
"0","0","printerPort",,"0"
"0","0","RBFetchData","DefaultReceiptDataFetch","0"
"0","0","RBFilter","DefaultReceiptFilter","0"
"0","0","RBSort","DefaultReceiptSort","0"
"0","0","RBTag","DefaultReceiptTag","0"
"0","0","ReceiptDriver","ESCPOSPrintHandler","0"
"0","0","ReceiptMessageMods",,"1"
"0","0","refundDiscountable","0","0"
"0","0","RestrictDefaultNonMem","0","0"
"0","0","roundUpDept","701","0"
"0","0","scaleDriver","NewMagellan","0"
"0","0","scalePort",,"0"
"0","0","screenLines","11","0"
"0","0","SecurityCancel","20","0"
"0","0","SecurityLineItemDiscount","20","0"
"0","0","SecurityRefund","20","0"
"0","0","SecuritySR","20","0"
"0","0","SecurityTR","20","0"
"0","0","SpecialUpcClasses",,"1"
"0","0","store",,"0"
"0","0","TenderReportMod","DefaultTenderReport","0"
"0","0","timeout","180000","0"
"0","0","TotalActions",,"1"
"0","0","touchscreen",,"0"
"0","0","UpcIncludeCheckDigits","0","0"
"0","0","useMemTypeTable","0","0"
"0","0","VariableWeightReWriter","ZeroedPriceReWrite","0"
"0","0","visitingMem",,"0"
"0","0","VoidLimit","0","0"
"0","1","alertBar",,"0"
"0","1","ArDepartments","0","1"
"0","1","BottleReturnDept",,"0"
"0","1","CancelReceipt","0","0"
"0","1","cashOverLimit","0","0"
"0","1","CouponsAreTaxable","1","0"
"0","1","CustomerDisplay","0","0"
"0","1","Debug_CoreLocal","0","0"
"0","1","Debug_Redirects","0","0"
"0","1","defaultNonMem","999","0"
"0","1","DiscountableSaleItems","1","0"
"0","1","discountEnforced","1","0"
"0","1","DiscountModule","DiscountModule","0"
"0","1","DiscountTypeClasses",,"1"
"0","1","dollarOver","0","0"
"0","1","dualDrawerMode","0","0"
"0","1","EanIncludeCheckDigits","0","0"
"0","1","emailReceiptFrom",,"0"
"0","1","emailReceiptHost","127.0.0.1","0"
"0","1","emailReceiptHtml",,"0"
"0","1","emailReceiptName","CORE-POS","0"
"0","1","emailReceiptPort","25","0"
"0","1","emailReceiptPw",,"0"
"0","1","emailReceiptSmtp","0","0"
"0","1","emailReceiptSSL","none","0"
"0","1","emailReceiptUser",,"0"
"0","1","enableFranking","0","0"
"0","1","EquityDepartments","0","1"
"0","1","fntlDefault","1","0"
"0","1","FooterModules","SavedOrCouldHave,TransPercentDiscount,MemSales,EveryoneSales,MultiTotal","1"
"0","1","houseCouponPrefix","00499999","0"
"0","1","ItemNotFound","ItemNotFound","0"
"0","1","kickerModule","Kicker","0"
"0","1","LineItemDiscountMem","0","0"
"0","1","LineItemDiscountNonMem","0","0"
"0","1","locale","en_US","0"
"0","1","lockScreen","1","0"
"0","1","LoudLogins","1","0"
"0","1","mDatabase","core_server","0"
"0","1","mDBMS","PDO_MYSQL","0"
"0","1","member_subtotal","1","0"
"0","1","memlistNonMember","0","0"
"0","1","mPass","\*\*\*\*\*\*\*\*","0"
"0","1","mServer","localhost","0"
"0","1","mUser","\*\*\*\*\*\*\*\*","0"
"0","1","newReceipt","2","0"
"0","1","NonStackingDiscounts","0","0"
"0","1","Notifiers",,"1"
"0","1","PriceMethodClasses",,"1"
"0","1","print","1","0"
"0","1","printerPort",,"0"
"0","1","RBFetchData","DefaultReceiptDataFetch","0"
"0","1","RBFilter","DefaultReceiptFilter","0"
"0","1","RBSort","DefaultReceiptSort","0"
"0","1","RBTag","DefaultReceiptTag","0"
"0","1","ReceiptDriver","ESCPOSPrintHandler","0"
"0","1","receiptHeader1","George Street Co-op","0"
"0","1","receiptHeader2","natural foods market & cafe","0"
"0","1","receiptHeader3","89 Morris Street","0"
"0","1","receiptHeader4","New Brunswick, NJ 08901","0"
"0","1","receiptHeader5","732-247-8280","0"
"0","1","receiptHeader6","www.georgestreetcoop.com","0"
"0","1","receiptHeaderCount","6","0"
"0","1","ReceiptLocalMode","total","0"
"0","1","ReceiptMessageMods",,"1"
"0","1","ReceiptSavingsMode","DefaultReceiptSavings","0"
"0","1","refundDiscountable","1","0"
"0","1","RestrictDefaultNonMem","0","0"
"0","1","roundUpDept","701","0"
"0","1","scaleDriver","ssd","0"
"0","1","screenLines","11","0"
"0","1","SecurityCancel","20","0"
"0","1","SecurityLineItemDiscount","20","0"
"0","1","SecurityRefund","20","0"
"0","1","SecuritySR","20","0"
"0","1","SecurityTR","20","0"
"0","1","ShrinkReceipt","0","0"
"0","1","SpecialUpcClasses",,"1"
"0","1","store",,"0"
"0","1","SuspendReceipt","0","0"
"0","1","TenderHardMinMax","0","0"
"0","1","TenderMap",,"1"
"0","1","TenderReportMod","DefaultTenderReport","0"
"0","1","timeout","180000","0"
"0","1","TotalActions",,"1"
"0","1","touchscreen","0","0"
"0","1","UpcIncludeCheckDigits","0","0"
"0","1","useMemTypeTable","0","0"
"0","1","VariableWeightReWriter","ZeroedPriceReWrite","0"
"0","1","visitingMem",,"0"
"0","1","VoidLimit","0","0"


**ini.php** (comment lines deleted)
```php
<?php
if (!isset($CORE_LOCAL))
	require_once(realpath(dirname(__FILE__).'/lib/LocalStorage/conf.php'));
$CORE_LOCAL->set('LaneMap', array(
    '192.168.1.51' => array('register_id' => 1, 'store_id' => 1),
    '192.168.1.52' => array('register_id' => 2, 'store_id' => 1),
    '192.168.1.53' => array('register_id' => 3, 'store_id' => 1),
));
@include_once(dirname(__FILE__).'/ini-local.php');
```

**ini-local.php** (comment lines deleted)
```php
<?php
if (!isset($CORE_LOCAL))
	require_once(realpath(dirname(__FILE__).'/lib/LocalStorage/conf.php'));

$CORE_LOCAL->set('store_id',1, True);
$CORE_LOCAL->set('store','GeorgeStreetCoop', True);
$CORE_LOCAL->set('laneno',1, True);

$CORE_LOCAL->set('mDBMS','pdomysql', True);
$CORE_LOCAL->set('mServer','localhost', True);
$CORE_LOCAL->set('mUser','\*\*\*\*\*\*\*\*', True);
$CORE_LOCAL->set('mPass','\*\*\*\*\*\*\*\*', True);
$CORE_LOCAL->set('mDatabase','core_server', True);

$CORE_LOCAL->set('DBMS','PDO_MYSQL', True);
$CORE_LOCAL->set('localhost','localhost', True);
$CORE_LOCAL->set('localUser','\*\*\*\*\*\*\*\*', True);
$CORE_LOCAL->set('localPass','\*\*\*\*\*\*\*\*', True);
$CORE_LOCAL->set('tDatabase','core_translog', True);
$CORE_LOCAL->set('pDatabase','core_opdata', True);

$CORE_LOCAL->set('print',1, True);
$CORE_LOCAL->set('newReceipt',1, True);
$CORE_LOCAL->set('printerPort','/dev/ttyS1', True);

$CORE_LOCAL->set('trainingMsgCount',0, True);
$CORE_LOCAL->set('alertBar','Lane 1', True);

$CORE_LOCAL->set('ccLive',0, True);

$CORE_LOCAL->set('lockScreen',1, True);
$CORE_LOCAL->set('scalePort','/dev/ttyS0', True);
$CORE_LOCAL->set('timeout','180000', True);
```

**Comment by gohanman** [comment] 2016-01-17 00:26
The simplest solution is probably to just delete ini-local.php. In this
particular instance the newReceipt setting is conflicting, but I don't
think ini-local.php serves any practical purpose at his point.

**Comment by scannerdarkly** [comment] 2016-01-17 00:35
Deleted **ini-local.php**, signed out, signed in, did single-item transaction. Still no items listed on receipt, and it **queries.log** showed the same error message yet again.

**Comment by gohanman** [comment] 2016-01-17 00:40
Closing and re-opening the browser might give you a more complete reset of
the session.

**Comment by scannerdarkly** [comment] 2016-01-17 01:58
Signout out of CORE-POS, closed browser, rebooted machine, started browser, signed in, did single-item transaction. Still no items listed on receipt, **queries.log** shows the same error message. :(

I guess I'll

**Comment by scannerdarkly** [comment] 2016-01-17 01:59
Signout out of CORE-POS, closed browser, rebooted machine, started browser, signed in, did single-item transaction. Still no items listed on receipt, queries.log shows the same error message. :(

**Comment by scannerdarkly** [comment] 2016-01-17 02:00
Sorry about clumsily closing and reopening this issue. My doing so was **not** some sort of meta-commentary on closing and re-opening the browser. :)

**Comment by scannerdarkly** [comment] 2016-01-17 13:46
It feels like it's time for me to insert some tracing code into the codebase. Since I don't know the architecture yet: It is at least correct that **ajax-end.php** is firing at that moment, right?

**Comment by gohanman** [comment] 2016-01-17 14:51
Yes. It sounds more specifically like the problem is here:
https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/lib/ReceiptLib.php#L772

And the newReceipt setting is getting changed by something. Turning on
state logging on the debug tab will list changes to all CoreLocal values
and should show some hint about when it's changing.

**Comment by scannerdarkly** [comment] 2016-01-18 05:16
I figured out the problem, I think. I was using a symlink to point from the CORE-POS tree to an **ini.php** and an **ini-local.php** that are both kept in my own GitHub repository. When I *thought* I was deleting **ini-local.php** I was only deleting the symlink in the CORE-POS tree, and the system was still finding my own **ini.php** and **ini-local.php** and running them. Since **ini-local.php** was still specifying `newReceipt=1`, and since that contradicted the setting in **parameters**, I suspect CORE-POS found itself in a place where none of the various `if` tests would be satisfied, and thus no item printout code would execute.

Setting `newReceipt=2` in my **ini-local.php** made everything good again.

@gohanman, it looks like the original purpose of **ini-local.php** (having system-wide settings but letting individual lanes specify their own exceptions) has been superseded by having the **parameters** tables? If so, is there a place to go to see which settings must reside in **ini.php**, and the ideal relationship between the office **parameters** and individual lane **parameters**?

**Comment by gohanman** [comment] 2016-01-18 15:09
Essentially lane#, store#, and the lane database credentials go in ini.php and everything else goes in parameters (hovering the cursor on a setting usually shows where it's stored). System-wide and lane-specific settings can co-exist in the parameters table. Records with lane_id=0 are system-wide and lane_id=non-zero are lane-specific. If both exist for a given param_key, the lane-specific setting takes precedence (on that particular lane).

**Comment by gohanman** [comment] 2016-01-18 15:39
Odd. Automatic commit linking appears to have failed.
515e013fe9c391209d666158416f9cb2ddd82ec0

As discussed earlier, this removes the messier views and related receipt option entirely on new installs. Existing installs should not be impacted as no views are removed without manual user intervention.

**Comment by scannerdarkly** [comment] 2016-01-18 16:58
Okay,that makes sense — and office syncs its full **parameters** table over to the lanes like with the other synchronized tables?

**Comment by gohanman** [comment] 2016-01-18 17:08
Yep.

**Comment by flathat** [comment] 2016-01-18 17:26
> office syncs its full parameters table over to the lanes like with the other synchronized tables?
> Yep.

It could, but utilities such as `LaneSyncTask` don't by default.

**Comment by scannerdarkly** [comment] 2016-01-18 21:36
Nice, thanks guys!

**Comment by scannerdarkly** [comment] 2016-01-18 21:36
(Do I close this issue? Or is that for you guys to say?)

**Comment by gohanman** [comment] 2016-01-18 21:37
I was thinking more of a manual sync after making changes on the server-side table. I don't see any good reason for a nightly sync. It's much too slow to be useful (change a lane config option and check tomorrow to see if it worked?) and could make a mess if someone *isn't* managing settings centrally.

**Comment by gohanman** [comment] 2016-01-18 21:57
There aren't any rules about issues. I prune the list periodically to get rid of issues that appear resolved, but I think it's always fair game to close one that you opened (or re-open it if needed).

**Closed by gohanman** 2016-01-18 21:57 UTC

**Comment by scannerdarkly** [comment] 2016-01-18 22:01
Okay, thanks. :)
